import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Area, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis, Brush, Scatter } from 'recharts';
import { MapContainer, TileLayer, GeoJSON } from 'react-leaflet';
import L from 'leaflet';
import { Sprout, LayoutDashboard, Map, Activity, FlaskConical, Table2, Download, ArrowUpRight, Radio, Search, ChevronRight, RefreshCw } from 'lucide-react';
import { api, queryString } from './api';
import { exportChart } from './exportChart';
import 'leaflet/dist/leaflet.css';
import './style.css';

type Entity = {id:string; name:string; [key:string]:unknown};
type Reading = {sensor_id:string; timestamp:string; value:number|null; anomaly?:boolean; quality?:string[]; measurement?:string; anomalies?:number};
type Dashboard = {active_sensors:number; offline_sensors:number; fields:number; plots:number; experiments:number; readings:number; anomalies:number; quality_warnings:number; recent:Reading[]};
const tabs = [{name:'Overview', icon:LayoutDashboard},{name:'Field map',icon:Map},{name:'Time series',icon:Activity},{name:'Experiments',icon:FlaskConical},{name:'Data explorer',icon:Table2}];
const colors = ['#3c8060','#c2944d','#617d9a','#a16c85','#6c995b','#655d97'];

function App() {
  const [tab,setTab] = useState('Overview');
  const [metadata,setMetadata] = useState<Record<string,Entity[]>>({});
  const [dashboard,setDashboard] = useState<Dashboard>();
  const [geo,setGeo] = useState<GeoJSON.FeatureCollection>();
  const [series,setSeries] = useState<Reading[]>([]);
  const [rows,setRows] = useState<Reading[]>([]);
  const [total,setTotal] = useState(0);
  const [page,setPage] = useState(1);
  const [filters,setFilters] = useState<Record<string,string>>({measurement:'soil_moisture'});
  const [hours,setHours] = useState('24');
  const [error,setError] = useState('');
  const [updated,setUpdated] = useState('');
  const [selected,setSelected] = useState<Entity>();
  const [detail,setDetail] = useState<Record<string,unknown>>();
  const [token,setToken] = useState('');
  const [showQuality,setShowQuality] = useState(true);
  const [order,setOrder] = useState('desc');
  const qs = queryString(filters);
  useEffect(() => { Promise.all(['farms','fields','plots','crops','experiments','sensors','treatments','seasons','notes'].map(async key => [key,(await api<{items:Entity[]}>(`/${key}?size=500`)).items] as const)).then(entries=>setMetadata(Object.fromEntries(entries))).catch(e=>setError(e.message)); api<GeoJSON.FeatureCollection>('/map').then(setGeo).catch(e=>setError(e.message)); },[]);
  useEffect(() => {
    let active=true;
    const refresh = async () => {
      try {
        const [d,s,r] = await Promise.all([api<Dashboard>('/dashboard'),api<{items:Reading[]}>(`/series?${qs}&hours=${hours}`),api<{items:Reading[];total:number}>(`/readings?${qs}&page=${page}&size=50&order=${order}`)]);
        if(active){setDashboard(d);setSeries(s.items);setRows(r.items);setTotal(r.total);setUpdated(new Date().toLocaleTimeString());setError('');}
      } catch(e) {if(active)setError((e as Error).message);}
    }; void refresh(); const timer=setInterval(refresh,15000); return()=>{active=false;clearInterval(timer);};
  },[qs,hours,page,order]);
  const changeFilter = (key:string,value:string) => {setFilters(f=>({...f,[key]:value}));setPage(1);};
  const inspect = async (entity:Entity,kind:string) => {setSelected({...entity,kind});setDetail(undefined);if(kind==='sensor'){changeFilter('sensor',entity.id);try{setDetail(await api(`/sensors/${entity.id}`));}catch(e){setError((e as Error).message);}} else if(kind==='plot'||kind==='field')changeFilter(kind,entity.id);};
  const sensorIds = [...new Set(series.map(r=>r.sensor_id))].slice(0,6);
  const observedTimes = [...new Set(series.map(r=>r.timestamp))].sort();
  const times: string[] = [];
  if (observedTimes.length) { const end = Date.parse(observedTimes[observedTimes.length-1]); for(let t=Date.parse(observedTimes[0]);t<=end;t+=Number(hours)*3600000) times.push(new Date(t).toISOString()); }
  const chartData = times.map(timestamp=>{const record:Record<string,string|number|null>={timestamp,label:new Date(timestamp).toLocaleDateString(undefined,{month:'short',day:'numeric'})}; sensorIds.forEach(id=>{const r=series.find(r=>Date.parse(r.timestamp)===Date.parse(timestamp)&&r.sensor_id===id);record[id]=r?.value??null;record[id+'-anomaly']=r?.anomalies?r.value:null;});return record;});
  const name = (key:string,id:unknown) => metadata[key]?.find(e=>e.id===id)?.name || String(id||'—');
  const exportLink = '/api/exports/csv?'+qs;
  const chart = <div className="chart"><ResponsiveContainer width="100%" height={300}><ComposedChart data={chartData} margin={{top:15,right:20,bottom:0,left:0}}><CartesianGrid strokeDasharray="3 5" vertical={false} stroke="#e5e9e3"/><XAxis dataKey="label" minTickGap={45} tick={{fontSize:11}}/><YAxis tick={{fontSize:11}} width={42}/><Tooltip labelFormatter={(_,payload)=>payload?.[0]?.payload?.timestamp ? new Date(payload[0].payload.timestamp).toLocaleString() : ''}/>{sensorIds.flatMap((id,i)=>[i===0?<Area key={id} isAnimationActive={false} type="monotone" dataKey={id} name={name('sensors',id)} stroke={colors[i]} fill="#e5eee4" connectNulls={false}/>:<Line key={id} isAnimationActive={false} type="monotone" dataKey={id} name={name('sensors',id)} stroke={colors[i]} dot={false} connectNulls={false}/>,<Scatter key={id+'-anomaly'} isAnimationActive={false} dataKey={id+'-anomaly'} name="Flagged bucket" fill="#d77745"/>])}<Brush dataKey="label" height={20} stroke="#9baa98"/></ComposedChart></ResponsiveContainer><div className="legend">{sensorIds.map((id,i)=><span key={id}><i style={{background:colors[i]}}/>{name('sensors',id)}</span>)}</div><small>Hourly/daily means · orange markers indicate anomalous readings within a bucket · up to six series shown. Blank intervals are missing data.</small></div>;
  const map = geo && <MapContainer center={[40.051,-83.05]} zoom={13} scrollWheelZoom={false} className="map"><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><GeoJSON data={geo} style={feature=>({color:feature?.properties.kind==='field'?'#426c40':'#b39756',weight:2,fillOpacity:.17})} pointToLayer={(_,latlng)=>L.circleMarker(latlng,{radius:4,color:'#fafbf6',weight:1,fillColor:'#245844',fillOpacity:1})} onEachFeature={(feature,layer)=>{layer.bindTooltip(String(feature.properties.name));layer.on('click',()=>void inspect(feature.properties as Entity,feature.properties.kind));}}/></MapContainer>;
  return <div className="shell"><aside><a className="brand" href="#" onClick={()=>setTab('Overview')}><span><Sprout size={26}/></span>FieldSense<span className="brand-dot">.</span></a><div className="workspace"><span className="avatar">FS</span><div>Field Systems Lab<small>Research workspace</small></div></div><div className="nav-label">WORKSPACE</div><nav>{tabs.map(({name,icon:Icon})=><button key={name} className={tab===name?'active':''} onClick={()=>{setTab(name);setSelected(undefined);}}><Icon size={18}/>{name}{tab===name&&<ChevronRight size={15}/>}</button>)}</nav><div className="aside-bottom"><div className="season"><Sprout size={18}/><strong>Growing knowledge<small>One measurement at a time.</small></strong></div><span className="avatar">DR</span><div>Demo researcher<small>Simulated research environment</small></div></div></aside><main><header><span>Workspace <ChevronRight size={13}/> <strong>{tab}</strong></span><span className="sync"><i/> Updates every 15 seconds</span></header><div className="content"><div className="page-heading"><div><div className="eyebrow">FIELD RESEARCH / DATA WORKSPACE</div><h1>{tab==='Overview'?'A clearer picture of your fields.':tab}</h1><p>{tab==='Overview'?'From the soil to the season. Explore your experiments in one place.':'Explore measurements, understand field conditions, and prepare your research.'}</p></div><a className="button" href={exportLink}><Download size={16}/> Export data</a></div><div className="demo-banner"><Sprout size={15}/><strong>Simulated research dataset</strong><span>3 farms · 60 days of measurements · intentionally imperfect sensor data</span></div>{error&&<div role="alert" className="error">{error} <button onClick={()=>window.location.reload()}>Retry</button></div>}
  <section className="filters" aria-label="Data filters">{[['farm','farms'],['field','fields'],['plot','plots'],['crop','crops'],['experiment','experiments'],['sensor','sensors']].map(([key,collection])=><label key={key}>{key}<select aria-label={key} value={filters[key]||''} onChange={e=>changeFilter(key,e.target.value)}><option value="">All {collection}</option>{metadata[collection]?.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label>)}<label>Measurement<select value={filters.measurement||''} onChange={e=>changeFilter('measurement',e.target.value)}>{['soil_moisture','soil_temperature','air_temperature','humidity','rainfall','canopy_temperature','par','leaf_wetness'].map(m=><option key={m}>{m}</option>)}</select></label><label>From<input type="date" value={filters.start?.slice(0,10)||''} onChange={e=>changeFilter('start',e.target.value?e.target.value+'T00:00:00Z':'')}/></label><label>Through<input type="date" value={filters.end?.slice(0,10)||''} onChange={e=>changeFilter('end',e.target.value?e.target.value+'T23:59:59Z':'')}/></label><button className="reset" onClick={()=>{setFilters({measurement:'soil_moisture'});setPage(1);}}>Reset</button></section>
  {!dashboard&&!error&&<p role="status">Connecting to research data…</p>}
  {tab==='Overview'&&dashboard&&<><div className="stats">{[['Active sensors',dashboard.active_sensors,`${dashboard.offline_sensors} offline · 6-hour threshold`],['Research fields',dashboard.fields,`${dashboard.plots} experimental plots`],['Measurements',dashboard.readings.toLocaleString(),'Stored sensor observations'],['Anomaly flags',dashboard.anomalies,`${dashboard.quality_warnings} missing-value warnings`]].map(([label,value,sub],i)=><article className="stat" key={label}><div>{label}<span>{i===0?<Radio size={17}/>:i===3?<Activity size={17}/>:<Sprout size={17}/>}</span></div><strong>{value}</strong><small><i className={i===3?'amber':''}/>{sub}</small></article>)}</div><div className="dashboard-grid"><section className="panel"><div className="panel-heading"><div><h2>What’s happening below the surface</h2><p>{filters.measurement.replaceAll('_',' ')} · aggregated measurements</p></div><select aria-label="Aggregation" value={hours} onChange={e=>setHours(e.target.value)}><option value="24">Daily means</option><option value="6">6-hour means</option><option value="168">Weekly means</option></select></div>{chart}</section><section className="panel map-panel"><div className="panel-heading"><div><h2>Your research landscape</h2><p>Click a boundary or sensor to inspect</p></div><button aria-label="Expand field map" onClick={()=>setTab('Field map')}><ArrowUpRight size={19}/></button></div>{map}<div className="map-caption"><span><i/> Field boundaries</span><span>WGS84 · simulated locations</span></div></section></div><div className="bottom-grid"><section className="panel"><div className="panel-heading"><div><h2>Experiments in the field</h2><p>Explore the questions behind your data</p></div><button onClick={()=>setTab('Experiments')}>View all <ArrowUpRight size={14}/></button></div>{metadata.experiments?.slice(0,3).map(e=><button className="experiment-row" key={e.id} onClick={()=>{setTab('Experiments');setSelected(e);}}><span className="crop-icon"><Sprout/></span><div><strong>{e.name}</strong><small>{name('crops',e.crop_id)} · {metadata.plots?.filter(p=>p.experiment_id===e.id).length} plots</small></div><span className="pill">Research trial</span><ChevronRight size={16}/></button>)}</section><section className="panel activity"><h2>Latest observations</h2><p>Most recently received sensor data</p>{dashboard.recent.map((r,i)=><div className="activity-row" key={i}><span className="activity-dot"/><div><strong>{name('sensors',r.sensor_id)}</strong><small>{r.value??'Missing'} · {new Date(r.timestamp).toLocaleString()}</small></div></div>)}</section></div></>}
  {tab==='Field map'&&<section className="panel full-map">{map}</section>}
  {tab==='Time series'&&<section className="panel"><div className="panel-heading"><h2>Measurement history</h2><label>Aggregation <select value={hours} onChange={e=>setHours(e.target.value)}>{[1,6,24,168].map(h=><option key={h} value={h}>{h} hours</option>)}</select></label><button onClick={()=>void exportChart().catch(e=>setError(e.message))}><Download size={15}/> Save PNG</button><button onClick={()=>window.print()}><Download size={15}/> Print / save PDF</button></div>{series.length?chart:<p>No measurements match these filters.</p>}</section>}
  {tab==='Data explorer'&&<section className="panel"><div className="panel-heading"><h2>Research observations <small>{total.toLocaleString()} matches</small></h2><label><input type="checkbox" checked={showQuality} onChange={e=>setShowQuality(e.target.checked)}/> Quality columns</label><button onClick={()=>setOrder(o=>o==='desc'?'asc':'desc')}>Timestamp {order==='desc'?'↓':'↑'}</button></div><div className="table-scroll"><table><thead><tr><th>Sensor</th><th>Timestamp (local)</th><th>Measurement</th><th>Value</th>{showQuality&&<><th>Anomaly</th><th>Quality</th></>}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td><button onClick={()=>void inspect({id:r.sensor_id,name:name('sensors',r.sensor_id)},'sensor')}>{name('sensors',r.sensor_id)}</button></td><td>{new Date(r.timestamp).toLocaleString()}</td><td>{r.measurement?.replaceAll('_',' ')}</td><td>{r.value??'—'}</td>{showQuality&&<><td>{r.anomaly?'Flagged':'—'}</td><td>{r.quality?.join(', ')||'Recorded'}</td></>}</tr>)}</tbody></table></div>{!rows.length&&<p>No readings match your filters.</p>}<div className="pagination"><span>Page {page} of {Math.max(1,Math.ceil(total/50))}</span><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><button disabled={page*50>=total} onClick={()=>setPage(p=>p+1)}>Next</button></div></section>}
  {tab==='Experiments'&&<div className="experiment-grid"><section className="panel"><div className="panel-heading"><h2>Research trials</h2><FlaskConical size={20}/></div>{metadata.experiments?.map(e=><button className="experiment-row" key={e.id} onClick={()=>{setSelected(e);changeFilter('experiment',e.id);}}><span className="crop-icon"><Sprout/></span><div><strong>{e.name}</strong><small>{name('crops',e.crop_id)} · {String(e.start_date)} — {String(e.end_date)}</small></div><ChevronRight/></button>)}</section><section className="panel form-panel"><h2>Create an experiment</h2><p>A lab write token is required to make changes.</p><form onSubmit={async event=>{event.preventDefault();const f=new FormData(event.currentTarget);try{const e=await api<Entity>('/experiments',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({name:f.get('name'),description:f.get('description'),crop_id:f.get('crop'),season_id:metadata.seasons?.[0]?.id,start_date:f.get('start'),end_date:f.get('end'),treatments:String(f.get('treatments')).split(',').map(t=>t.trim()).filter(Boolean)})});setMetadata(m=>({...m,experiments:[...m.experiments,e]}));setSelected(e);setError('');}catch(e){setError((e as Error).message);}}}><label>Lab write token<input type="password" required value={token} onChange={e=>setToken(e.target.value)} autoComplete="off"/></label><label>Title<input name="name" required minLength={3}/></label><label>Research question<textarea name="description" required/></label><label>Crop<select name="crop">{metadata.crops?.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><div className="date-pair"><label>Start<input type="date" name="start" required/></label><label>End<input type="date" name="end" required/></label></div><label>Treatments, separated by commas<input name="treatments" placeholder="Rainfed control, Supplemental irrigation" required/></label><button className="button" type="submit">Create experiment</button></form></section></div>}
  {selected&&<section className="panel detail"><div className="panel-heading"><h2>{selected.name}</h2><button onClick={()=>setSelected(undefined)}>Close</button></div><p>{String(selected.description||'Selected research location or instrument')}</p><dl>{Object.entries(selected).filter(([k,v])=>k!=='name'&&typeof v==='string').map(([k,v])=><React.Fragment key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{String(v)}</dd></React.Fragment>)}</dl>{selected.kind==='sensor'&&<><h3>Instrument & deployment history</h3><pre>{JSON.stringify(detail,null,2)}</pre><label>Lab write token<input type="password" value={token} onChange={e=>setToken(e.target.value)}/></label><button onClick={async()=>{try{const r=await api<{anomalies:number}>(`/sensors/${selected.id}/detect`,{method:'POST',headers:{Authorization:'Bearer '+token}});setError('');setDetail(d=>({...d,detection:r}));}catch(e){setError((e as Error).message);}}}>Fit anomaly detector</button></>}{tab==='Experiments'&&<><form onSubmit={async event=>{event.preventDefault();const f=new FormData(event.currentTarget);try{const note=await api<Entity>('/notes',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({experiment_id:selected.id,body:f.get('body')})});setMetadata(m=>({...m,notes:[...m.notes,note]}));setError('');}catch(e){setError((e as Error).message);}}}><label>Lab write token<input type="password" required value={token} onChange={e=>setToken(e.target.value)}/></label><label>Research note<textarea name="body" required/></label><button type="submit">Add note</button></form><p>{metadata.plots?.filter(p=>p.experiment_id===selected.id).map(p=>p.name).join(' · ')||'No plots assigned yet.'}</p>{metadata.notes?.filter(n=>n.experiment_id===selected.id).map(n=><blockquote key={n.id}>{String(n.body)}</blockquote>)}</>}<button onClick={()=>setTab('Time series')}>Explore selected measurements <ArrowUpRight size={14}/></button>{chart}</section>}
  <footer><span><Sprout size={14}/> FieldSense · Built for field research</span><span><RefreshCw size={12}/> {updated?'Last refreshed '+updated:'Waiting for data'} · <a href="/docs">API documentation</a></span></footer></div></main></div>;
}

createRoot(document.getElementById('root')!).render(<App/>);
